apiVersion: v1
kind: Service
metadata: 
  name: techchallengeapp-lb
  labels: 
    app: techchallengeapp
spec:
  type: LoadBalancer
  selector:
    app: techchallengeapp
  ports:
    - port: 80
      targetPort: 8080
